import logging
import shutil
import subprocess
import sys
import uuid
from pathlib import Path
from tempfile import TemporaryDirectory

from langchain_core.tools import tool

logger = logging.getLogger(__name__)

# 安全限制
MAX_PDF_SIZE_MB = 50
LATEX_TIMEOUT = 60  # 编译超时（秒）
LATEXMK_CMD = "latexmk"

@tool
def render_latex_pdf(latex_content: str) -> str:
    """Render a LaTeX document to PDF.

    Args:
        latex_content: The LaTeX document content as a string

    Returns:
        Path to the generated PDF file
    """
    if not latex_content.strip():
        raise ValueError("LaTeX content must not be empty")

    # 检查 latexmk 是否可用
    if not shutil.which(LATEXMK_CMD):
        raise RuntimeError(
            f"{LATEXMK_CMD} not found. Please install a LaTeX distribution."
        )

    # 持久化输出目录
    output_dir = Path("output").absolute()
    output_dir.mkdir(exist_ok=True)

    try:
        # 使用临时目录进行编译，避免污染 output
        with TemporaryDirectory(prefix="latex_") as tmpdir_cm:
            tmpdir = Path(tmpdir_cm)

            # 使用唯一文件名，避免并发冲突
            unique_id = uuid.uuid4().hex[:12]
            tex_filename = f"doc_{unique_id}.tex"
            tex_file = tmpdir / tex_filename
            tex_file.write_text(latex_content, encoding="utf-8")
            logger.info("LaTeX source written to temp file")

            # 编译命令（禁用 shell-escape，防止命令注入）
            cmd = [
                LATEXMK_CMD,
                "-pdf",
                "-interaction=nonstopmode",
                "-pdflatex=pdflatex --no-shell-escape",
                str(tex_file),
            ]

            logger.info("Starting LaTeX compilation...")
            result = subprocess.run(
                cmd,
                cwd=tmpdir,
                capture_output=True,
                text=True,
                timeout=LATEX_TIMEOUT,
            )

            # 记录完整编译日志（debug 级别）
            logger.debug("latexmk stdout:\n%s", result.stdout)
            if result.stderr:
                logger.debug("latexmk stderr:\n%s", result.stderr)

            if result.returncode != 0:
                # 提取部分日志用于错误消息，避免返回整个输出
                log_tail = "\n".join(result.stderr.splitlines()[-20:])
                raise RuntimeError(f"LaTeX compilation failed:\n{log_tail}")

            # 生成后的 PDF 文件名
            pdf_tmp = tmpdir / f"doc_{unique_id}.pdf"
            if not pdf_tmp.exists():
                raise FileNotFoundError("PDF was not generated by latexmk")

            # 检查 PDF 大小
            pdf_size_mb = pdf_tmp.stat().st_size / (1024 * 1024)
            if pdf_size_mb > MAX_PDF_SIZE_MB:
                raise ValueError(
                    f"Generated PDF is too large ({pdf_size_mb:.1f} MB > {MAX_PDF_SIZE_MB} MB)"
                )

            # 复制到最终输出目录
            final_pdf = output_dir / f"doc_{unique_id}.pdf"
            shutil.copy2(pdf_tmp, final_pdf)
            logger.info("Successfully generated PDF: %s", final_pdf.name)
            return str(final_pdf)

    except subprocess.TimeoutExpired:
        logger.exception("LaTeX compilation timed out after %d seconds", LATEX_TIMEOUT)
        raise
    except Exception:
        logger.exception("Error rendering LaTeX")
        raise

    # 临时目录自动清理，所有辅助文件不再保留
    # 最终的 PDF 保留在 output/ 下（可配合定期清理策略）